//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRBOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADDRBOOK()
        {
            this.ARADDRESSes = new HashSet<ARADDRESS>();
        }
    
        public int ADDB_KEY { get; set; }
        public string ADDB_COMPANY { get; set; }
        public string ADDB_BRANCH { get; set; }
        public string ADDB_TAX_ID { get; set; }
        public string ADDB_ADDB_1 { get; set; }
        public string ADDB_ADDB_2 { get; set; }
        public string ADDB_ADDB_3 { get; set; }
        public string ADDB_PROVINCE { get; set; }
        public string ADDB_POST { get; set; }
        public string ADDB_PHONE { get; set; }
        public string ADDB_FAX { get; set; }
        public string ADDB_WEBSITE { get; set; }
        public int ADDB_BT { get; set; }
        public int ADDB_STA { get; set; }
        public string ADDB_REMARK { get; set; }
        public string ADDB_SEARCH { get; set; }
        public string ADDB_EMAIL { get; set; }
        public Nullable<int> ADDB_CONNECT { get; set; }
        public string ADDB_GPS_LAT_S { get; set; }
        public string ADDB_GPS_LONG_S { get; set; }
        public string ADDB_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARADDRESS> ARADDRESSes { get; set; }
    }
}
