//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLU
    {
        public int APPLU_KEY { get; set; }
        public int APPLU_APPRB { get; set; }
        public int APPLU_GOODS { get; set; }
        public decimal APPLU_U_PRC { get; set; }
        public string APPLU_U_DSC { get; set; }
        public string APPLU_LASTUPD { get; set; }
    
        public virtual GOODSMASTER GOODSMASTER { get; set; }
    }
}
