//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLOG
    {
        public int PID { get; set; }
        public string APP_NAME { get; set; }
        public Nullable<int> REFRECORDID { get; set; }
        public string MACHINE_NAME { get; set; }
        public string MODULE_NAME { get; set; }
        public string METHOD_NAME { get; set; }
        public string DOBYUSER { get; set; }
        public System.DateTime LOG_DT { get; set; }
        public string LOG_DETAILS { get; set; }
    }
}
