//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARADDRESS
    {
        public int ARA_KEY { get; set; }
        public int ARA_AR { get; set; }
        public int ARA_ADDB { get; set; }
        public string ARA_DEFAULT { get; set; }
        public string ARA_LASTUPD { get; set; }
    
        public virtual ADDRBOOK ADDRBOOK { get; set; }
        public virtual ARFILE ARFILE { get; set; }
    }
}
