//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARCAT()
        {
            this.ARFILEs = new HashSet<ARFILE>();
        }
    
        public int ARCAT_KEY { get; set; }
        public string ARCAT_CODE { get; set; }
        public string ARCAT_NAME { get; set; }
        public short ARCAT_ACCESS { get; set; }
        public decimal ARCAT_UDF_1 { get; set; }
        public decimal ARCAT_UDF_2 { get; set; }
        public decimal ARCAT_UDF_3 { get; set; }
        public decimal ARCAT_UDF_4 { get; set; }
        public decimal ARCAT_UDF_5 { get; set; }
        public decimal ARCAT_UDF_6 { get; set; }
        public string ARCAT_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARFILE> ARFILEs { get; set; }
    }
}
