//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARFILE()
        {
            this.ARADDRESSes = new HashSet<ARADDRESS>();
        }
    
        public int AR_KEY { get; set; }
        public string AR_CODE { get; set; }
        public string AR_NAME { get; set; }
        public int AR_ARCAT { get; set; }
        public int AR_AC { get; set; }
        public string AR_ENABLE { get; set; }
        public short AR_ACCESS { get; set; }
        public string AR_SLMNCODE { get; set; }
        public int AR_ARL { get; set; }
        public int AR_ARTY { get; set; }
        public int AR_ARG { get; set; }
        public int AR_ARR { get; set; }
        public int AR_ARGL { get; set; }
        public int AR_DEPT { get; set; }
        public string AR_REMARK { get; set; }
        public decimal AR_UDF_1 { get; set; }
        public decimal AR_UDF_2 { get; set; }
        public decimal AR_UDF_3 { get; set; }
        public decimal AR_UDF_4 { get; set; }
        public decimal AR_UDF_5 { get; set; }
        public decimal AR_UDF_6 { get; set; }
        public string AR_MBCODE { get; set; }
        public string AR_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARADDRESS> ARADDRESSes { get; set; }
        public virtual ARCAT ARCAT { get; set; }
        public virtual DEPTTAB DEPTTAB { get; set; }
    }
}
