//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARPRICETAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARPRICETAB()
        {
            this.ARPLUs = new HashSet<ARPLU>();
        }
    
        public int ARPRB_KEY { get; set; }
        public string ARPRB_CODE { get; set; }
        public string ARPRB_NAME { get; set; }
        public Nullable<int> ARPRB_VATIO { get; set; }
        public string ARPRB_ALWAYS { get; set; }
        public string ARPRB_ENABLE { get; set; }
        public string ARPRB_REMARK { get; set; }
        public string ARPRB_DEFAULT { get; set; }
        public string ARPRB_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARPLU> ARPLUs { get; set; }
    }
}
