//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANKINFO
    {
        public int BK_INFO_ID { get; set; }
        public int BK_ID { get; set; }
        public string BK_CODE { get; set; }
        public string BK_BRANCH { get; set; }
        public string BK_ACCOUNT_TYPE { get; set; }
        public string BK_ACCOUNT_NAME { get; set; }
        public string BK_ACCOUNT_NO { get; set; }
        public string BK_SWIFT { get; set; }
    }
}
