//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        public bool INACTIVE { get; set; }
        public int BANKID { get; set; }
        public string BANKCODE { get; set; }
        public string BANKNAME { get; set; }
        public string BANKTHNAME { get; set; }
        public string ACCOUNTBRANCH { get; set; }
        public string ACCOUNTTYPE { get; set; }
        public string ACCOUNTNAME { get; set; }
        public string ACCOUNTNO { get; set; }
        public string SWIFTCODE { get; set; }
    }
}
