//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public bool ISCOMPLETE { get; set; }
        public bool ISDELETE { get; set; }
        public bool ISCANCEL { get; set; }
        public Nullable<decimal> BILLCANCELDATE { get; set; }
        public string STATUS { get; set; }
        public string PREFIXID { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public Nullable<int> SALETYPE { get; set; }
        public int BILLID { get; set; }
        public string BILLNO { get; set; }
        public decimal BILLDATE { get; set; }
        public int FISCYEAR { get; set; }
        public int FISCPERIOD { get; set; }
        public decimal DUEDATE { get; set; }
        public decimal COLLECTDATE { get; set; }
        public int NUMOFDO { get; set; }
        public decimal TOTALVALUE { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal NETVALUE { get; set; }
        public decimal VATFACTOR { get; set; }
        public decimal TOTALVAT { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public string TOTALTEXT { get; set; }
        public Nullable<int> INVSEQ { get; set; }
        public string INVOICENO { get; set; }
        public decimal INVDATE { get; set; }
        public decimal TOTALPAYVALUE { get; set; }
        public decimal TOTALWHTAX { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
