//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLLINE
    {
        public int BILLLINGSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public int SALETYPE { get; set; }
        public int BILLID { get; set; }
        public int SOSEQ { get; set; }
        public string SONO { get; set; }
        public decimal SODATE { get; set; }
        public decimal TOTALVALUE { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal NETVALUE { get; set; }
        public decimal TOTALVAT { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
