//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_PROFILES
    {
        public int ID { get; set; }
        public string COMPANYID { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS { get; set; }
        public string PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL { get; set; }
        public string TAXID { get; set; }
        public string NON_VAT_RATE { get; set; }
        public string VAT_RATE { get; set; }
        public decimal NON_VAT_FACTOR { get; set; }
        public decimal VAT_FACTOR { get; set; }
        public decimal MATERIAL_MARKUP_FACTOR { get; set; }
        public string HOME_CURRENCY { get; set; }
        public string SOURCE_CURRENCY { get; set; }
        public Nullable<decimal> SOURCE_VALUE { get; set; }
        public string IMAGE_LOCATION { get; set; }
        public decimal PRODUCTION_HOUR_RATE { get; set; }
        public bool NONVAT_DISPLAY { get; set; }
    }
}
