//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int CONTACTID { get; set; }
        public string CONTACTNAME { get; set; }
        public string JOBTITLE { get; set; }
        public string COMPANY { get; set; }
        public string ADDR { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> LASTMODIFY { get; set; }
    }
}
