//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRCODE
    {
        public string CREDITCODE { get; set; }
        public string CREDITCODENAME { get; set; }
        public int DURATION { get; set; }
        public bool ISCANCEL { get; set; }
    }
}
