//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTPRICELIST
    {
        public int PRICESEQ { get; set; }
        public bool ISDELETE { get; set; }
        public string CUSTCODE { get; set; }
        public int CUSTID { get; set; }
        public string PREFIX { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public int PRODUCTSTYLE { get; set; }
        public int MATERIAL { get; set; }
        public string FLASK_TEMP { get; set; }
        public string CAST_TEMP { get; set; }
        public string BLOCKID { get; set; }
        public decimal WIDTH { get; set; }
        public decimal HEIGHT { get; set; }
        public decimal THICK { get; set; }
        public string SIZE { get; set; }
        public decimal WAXWEIGHT { get; set; }
        public decimal UNITWEIGHT { get; set; }
        public string UNITCOUNT { get; set; }
        public decimal CASTINGPRICE { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal SCOREPRICE { get; set; }
        public decimal PRICEEFFECTIVEDATE { get; set; }
        public decimal PRICEEXPIREDATE { get; set; }
        public bool HASBLOCK { get; set; }
        public string BLOCKLOC { get; set; }
        public bool HASPICTURE { get; set; }
        public string IMAGE_LOCATION { get; set; }
        public string AUDITUSER { get; set; }
        public System.DateTime DATEENTRY { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime DATEMODIFY { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
