//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTORDENTRY
    {
        public bool ISCOMPLETE { get; set; }
        public int ORDSEQ { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTORDER { get; set; }
        public decimal CUSTORDDATE { get; set; }
        public Nullable<decimal> ORDDELIVERYDATE { get; set; }
        public int TOTALLINEORDER { get; set; }
        public int TOTALLINECOMPLETE { get; set; }
    }
}
