//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTMATRETURN
    {
        public int RETSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public int SOSEQ { get; set; }
        public int CUSTMATSEQ { get; set; }
        public int GRVNO { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public string REFSONO { get; set; }
        public string REFMATDOC { get; set; }
        public string REFCUSTDOC { get; set; }
        public Nullable<int> FISCYEAR { get; set; }
        public Nullable<int> FISCPERIOD { get; set; }
        public decimal RETURNDATE { get; set; }
        public int RETURNMATTYPE { get; set; }
        public decimal RETURNWEIGHT { get; set; }
        public int DELIVERMATID { get; set; }
        public decimal MATFACTOR { get; set; }
        public decimal MAT_SI_PERCENT { get; set; }
        public decimal SI_QTY { get; set; }
        public string AUDITUSER { get; set; }
        public Nullable<System.DateTime> AUDITDATE { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
    
        public virtual MATRECEIVE MATRECEIVE { get; set; }
    }
}
