//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTASK
    {
        public int CTSEQ { get; set; }
        public bool ISDBCUST { get; set; }
        public bool ISTASKACTIVE { get; set; }
        public Nullable<int> CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string ADDR1 { get; set; }
        public string PROVINCE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string CONTACTNAME { get; set; }
        public string MOBILENO { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public string FACEBOOK { get; set; }
        public string SALENAME { get; set; }
        public int TASKONDATE { get; set; }
        public int TASKENDDATE { get; set; }
        public string REMARK { get; set; }
        public bool ACT_OFFER { get; set; }
        public bool ACT_MOREINFO { get; set; }
        public bool ACT_SERVICE { get; set; }
        public bool ACT_CONTACT { get; set; }
        public bool PRODUCT_CASTING { get; set; }
        public bool PRODUCT_BURNNER { get; set; }
        public bool PRODUCT_INVESTMENTMIX { get; set; }
        public bool PRODUCT_DIGITALWAX { get; set; }
        public bool PRODUCT_VULCANIZER { get; set; }
        public bool PRODUCT_POLISHING { get; set; }
        public bool PRODUCT_OTHERS { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
