//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTASKLINE
    {
        public int CTLSEQ { get; set; }
        public int CTSEQ { get; set; }
        public string TASKNAME { get; set; }
        public bool TASKVALUE { get; set; }
        public string TASKNOTE { get; set; }
    }
}
