//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTMOLD
    {
        public int MOLDSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public byte[] MOLDIMG { get; set; }
        public string ITEMPREFIX { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public int MOLDMATTYPE { get; set; }
        public int MOLDQTY { get; set; }
        public string MOLDRECEIVER { get; set; }
        public decimal MOLDRECEIVEDATE { get; set; }
        public int RETURNQTY { get; set; }
        public decimal MOLDRETURNDATE { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
