//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTPRICETAB
    {
        public int ID { get; set; }
        public int CPT_CP { get; set; }
        public int PRICE_YEAR { get; set; }
        public int MATERIAL { get; set; }
        public string PRICEUNITNAME { get; set; }
        public bool ISMATINCLUDE { get; set; }
        public decimal UNITPRICE { get; set; }
    }
}
