//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT1
    {
        public string DEPTID { get; set; }
        public string DEPTNAME { get; set; }
        public string DEPTMGR { get; set; }
    }
}
