//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPTTAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPTTAB()
        {
            this.ARFILEs = new HashSet<ARFILE>();
            this.TRANSTKHs = new HashSet<TRANSTKH>();
        }
    
        public int DEPT_KEY { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_THAIDESC { get; set; }
        public string DEPT_ENGDESC { get; set; }
        public string DEPT_DEFAULT { get; set; }
        public decimal DEPT_UDF_1 { get; set; }
        public decimal DEPT_UDF_2 { get; set; }
        public decimal DEPT_UDF_3 { get; set; }
        public decimal DEPT_UDF_4 { get; set; }
        public decimal DEPT_UDF_5 { get; set; }
        public decimal DEPT_UDF_6 { get; set; }
        public string DEPT_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARFILE> ARFILEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSTKH> TRANSTKHs { get; set; }
    }
}
