//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCINFO()
        {
            this.SKUBALANCEs = new HashSet<SKUBALANCE>();
            this.TRANSTKHs = new HashSet<TRANSTKH>();
            this.SKUMOVEs = new HashSet<SKUMOVE>();
        }
    
        public int DI_KEY { get; set; }
        public int DI_DT { get; set; }
        public Nullable<int> DI_SUBS_DI { get; set; }
        public Nullable<int> DI_REVISION { get; set; }
        public Nullable<int> DI_ACTIVE { get; set; }
        public Nullable<int> DI_EDIT_TIME { get; set; }
        public Nullable<int> DI_FLAG { get; set; }
        public string DI_REF { get; set; }
        public System.DateTime DI_DATE { get; set; }
        public System.DateTime DI_CRE_DATE { get; set; }
        public string DI_CRE_BY { get; set; }
        public string DI_CRE_CPTN { get; set; }
        public string DI_CRE_LGNN { get; set; }
        public System.DateTime DI_UPD_DATE { get; set; }
        public string DI_UPD_BY { get; set; }
        public string DI_UPD_CPTN { get; set; }
        public string DI_UPD_LGNN { get; set; }
        public Nullable<System.DateTime> DI_DEL_DATE { get; set; }
        public string DI_DEL_BY { get; set; }
        public string DI_DEL_CPTN { get; set; }
        public string DI_DEL_LGNN { get; set; }
        public short DI_PRN_TIME { get; set; }
        public Nullable<System.DateTime> DI_PRN_DATE { get; set; }
        public string DI_PRN_BY { get; set; }
        public string DI_PRN_CPTN { get; set; }
        public string DI_PRN_LGNN { get; set; }
        public Nullable<int> DI_PRN_STATUS { get; set; }
        public Nullable<System.DateTime> DI_EXM_DATE { get; set; }
        public string DI_EXM_BY { get; set; }
        public string DI_EXM_CPTN { get; set; }
        public string DI_EXM_LGNN { get; set; }
        public Nullable<System.DateTime> DI_APV_DATE { get; set; }
        public string DI_APV_BY { get; set; }
        public string DI_APV_CPTN { get; set; }
        public string DI_APV_LGNN { get; set; }
        public Nullable<int> DI_APV_STATUS { get; set; }
        public Nullable<int> DI_DFRS { get; set; }
        public Nullable<int> DI_1ST_ITEMS { get; set; }
        public decimal DI_1ST_AMOUNT { get; set; }
        public Nullable<int> DI_ITEMS { get; set; }
        public decimal DI_AMOUNT { get; set; }
        public Nullable<int> DI_AUTO { get; set; }
        public Nullable<int> DI_CREATOR_DI { get; set; }
        public string DI_REMARK { get; set; }
        public string DI_LASTUPD { get; set; }
    
        public virtual DOCTYPE DOCTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUBALANCE> SKUBALANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSTKH> TRANSTKHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUMOVE> SKUMOVEs { get; set; }
    }
}
