//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public bool ISRESIGN { get; set; }
        public int STATUS { get; set; }
        public string EMPCODE { get; set; }
        public string TITLENAME { get; set; }
        public string EMPFIRSTNAME { get; set; }
        public string EMPLASTNAME { get; set; }
        public string NICKNAME { get; set; }
        public int POSITIONID { get; set; }
        public int DEPARTMENTID { get; set; }
        public string GROUPACCOUNT { get; set; }
        public string COSTCENTER { get; set; }
        public decimal EMPLOYDATE { get; set; }
        public decimal RESIGNDATE { get; set; }
        public string WORK_DAYS { get; set; }
        public string IDCARDNUMBER { get; set; }
        public string CARDADDRESS1 { get; set; }
        public string CARDADDRESS2 { get; set; }
        public string CARDPROVINCE { get; set; }
        public string CARDCOUNTRY { get; set; }
        public string CARDZIPCODE { get; set; }
        public string CURRENTADDRESS1 { get; set; }
        public string CURRENTADDRESS2 { get; set; }
        public string CURRENTPROVINCE { get; set; }
        public string CURRENTCOUNTRY { get; set; }
        public string CURRENTZIPCODE { get; set; }
        public string HOMEPHONE { get; set; }
        public string CELLPHONE { get; set; }
        public string EMAIL { get; set; }
        public string SEX { get; set; }
        public decimal BIRTHDATE { get; set; }
        public int AGE { get; set; }
        public string EDUCATION { get; set; }
        public Nullable<int> PROBATIONDAY { get; set; }
        public decimal ENDPROBATIONDATE { get; set; }
        public int FAMILYSTATUS { get; set; }
        public int NUMBEROFKID { get; set; }
        public string ACCOUNTNUMBER { get; set; }
        public string BANKCODE { get; set; }
        public decimal DAYRATE { get; set; }
        public decimal MONTHRATE { get; set; }
    }
}
