//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPSAL
    {
        public int EMPSALSEQ { get; set; }
        public int YEARSAL { get; set; }
        public string EMPCODE { get; set; }
        public string EMPNAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string WORKGROUP { get; set; }
        public Nullable<decimal> CURRENT_SAL { get; set; }
        public decimal PSAL1 { get; set; }
        public decimal PSAL2 { get; set; }
        public decimal PSAL3 { get; set; }
        public decimal PSAL4 { get; set; }
        public decimal PSAL5 { get; set; }
        public decimal PSAL6 { get; set; }
        public decimal PSAL7 { get; set; }
        public decimal PSAL8 { get; set; }
        public decimal PSAL9 { get; set; }
        public decimal PSAL10 { get; set; }
        public decimal PSAL11 { get; set; }
        public decimal PSAL12 { get; set; }
        public decimal AVGHOURCOST { get; set; }
        public decimal ACTUALAVGHOURCOST { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
