//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENGINEER
    {
        public int engiseq { get; set; }
        public int Status { get; set; }
        public string id { get; set; }
        public string empcode { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string curr { get; set; }
        public int resigndate { get; set; }
    }
}
