//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP : DbContext
    {
        public ERP()
            : base("name=ERP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRBOOK> ADDRBOOKs { get; set; }
        public virtual DbSet<ARADDRESS> ARADDRESSes { get; set; }
        public virtual DbSet<ARCAT> ARCATs { get; set; }
        public virtual DbSet<ARFILE> ARFILEs { get; set; }
        public virtual DbSet<DEPTTAB> DEPTTABs { get; set; }
        public virtual DbSet<SALESMAN> SALESMen { get; set; }
        public virtual DbSet<SKUBALANCE> SKUBALANCEs { get; set; }
        public virtual DbSet<SKUMASTER> SKUMASTERs { get; set; }
        public virtual DbSet<SKUWARELOCATION> SKUWARELOCATIONs { get; set; }
        public virtual DbSet<DOCINFO> DOCINFOes { get; set; }
        public virtual DbSet<DOCTYPE> DOCTYPEs { get; set; }
        public virtual DbSet<TRANSTKD> TRANSTKDs { get; set; }
        public virtual DbSet<TRANSTKH> TRANSTKHs { get; set; }
        public virtual DbSet<PRJTAB> PRJTABs { get; set; }
        public virtual DbSet<ARPRICETAB> ARPRICETABs { get; set; }
        public virtual DbSet<UOFQTY> UOFQTies { get; set; }
        public virtual DbSet<ICCAT> ICCATs { get; set; }
        public virtual DbSet<ICDEPT> ICDEPTs { get; set; }
        public virtual DbSet<APPLU> APPLUs { get; set; }
        public virtual DbSet<GOODSMASTER> GOODSMASTERs { get; set; }
        public virtual DbSet<ARPLU> ARPLUs { get; set; }
        public virtual DbSet<SKUMOVE> SKUMOVEs { get; set; }
    }
}
