//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEF : DbContext
    {
        public ERPEF()
            : base("name=ERPEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRBOOK> ADDRBOOKs { get; set; }
        public virtual DbSet<ARADDRESS> ARADDRESSes { get; set; }
        public virtual DbSet<ARCAT> ARCATs { get; set; }
        public virtual DbSet<ARFILE> ARFILEs { get; set; }
        public virtual DbSet<DEPTTAB> DEPTTABs { get; set; }
        public virtual DbSet<SALESMAN> SALESMen { get; set; }
        public virtual DbSet<SKUBALANCE> SKUBALANCEs { get; set; }
        public virtual DbSet<SKUMASTER> SKUMASTERs { get; set; }
        public virtual DbSet<SKUWARELOCATION> SKUWARELOCATIONs { get; set; }
    }
}
