//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORLOG
    {
        public int ERRORLINE { get; set; }
        public System.DateTime ERRORDT { get; set; }
        public string APPNAME { get; set; }
        public string APPVERSION { get; set; }
        public string MODULE { get; set; }
        public string METHODNAME { get; set; }
        public string ERRORMSG { get; set; }
        public string USERNAME { get; set; }
        public string WORKSTATION { get; set; }
    }
}
