//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCHCURR
    {
        public int LINEID { get; set; }
        public string CURRENCY { get; set; }
        public decimal EXCHANGERATE { get; set; }
        public int FISCYEAR { get; set; }
        public int FISCPERIOD { get; set; }
        public decimal EFFECTIVEDT { get; set; }
        public decimal EXPIREDT { get; set; }
        public Nullable<byte> REVISION { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
        public Nullable<System.DateTime> BANKUPDATE { get; set; }
    }
}
