//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGLogInfo
    {
        public int logid { get; set; }
        public System.DateTime logdate { get; set; }
        public string workstation { get; set; }
        public string woker { get; set; }
        public string modulename { get; set; }
        public string action { get; set; }
        public string type { get; set; }
        public int recordid { get; set; }
        public Nullable<int> jobno { get; set; }
        public string partno { get; set; }
        public string partname { get; set; }
        public string unit { get; set; }
        public decimal qty { get; set; }
        public string material { get; set; }
        public decimal matweight { get; set; }
    }
}
