//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGSTOCK
    {
        public int FGSEQ { get; set; }
        public bool ISCOMPLETION { get; set; }
        public string APPCODE { get; set; }
        public int DOCNO { get; set; }
        public decimal DOCDATE { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public int MATID { get; set; }
        public string PREFIX { get; set; }
        public int ITEMID { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string UNIT { get; set; }
        public decimal QTY { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal UNITWEIGHT { get; set; }
        public decimal TOTALLINEWT { get; set; }
        public decimal DELIVERYQTY { get; set; }
        public Nullable<decimal> REMAINFG { get; set; }
        public decimal TOTALDELIVERYWT { get; set; }
        public Nullable<decimal> REMAINWEIGHT { get; set; }
        public string REMARK { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
