//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODSMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOODSMASTER()
        {
            this.APPLUs = new HashSet<APPLU>();
            this.SKUWARELOCATIONs = new HashSet<SKUWARELOCATION>();
            this.ARPLUs = new HashSet<ARPLU>();
        }
    
        public int GOODS_KEY { get; set; }
        public string GOODS_CODE { get; set; }
        public short GOODS_BARTYPE { get; set; }
        public int GOODS_SKU { get; set; }
        public int GOODS_UTQ { get; set; }
        public Nullable<decimal> GOODS_WEIGHT { get; set; }
        public Nullable<decimal> GOODS_VOLUME { get; set; }
        public string GOODS_ENABLE { get; set; }
        public string GOODS_P_ENABLE { get; set; }
        public string GOODS_MASTER { get; set; }
        public decimal GOODS_PRICE { get; set; }
        public string GOODS_ALIAS { get; set; }
        public string GOODS_E_ALIAS { get; set; }
        public string GOODS_PRT_BAR { get; set; }
        public string GOODS_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLU> APPLUs { get; set; }
        public virtual SKUMASTER SKUMASTER { get; set; }
        public virtual UOFQTY UOFQTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUWARELOCATION> SKUWARELOCATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARPLU> ARPLUs { get; set; }
    }
}
