//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICDEPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ICDEPT()
        {
            this.SKUMASTERs = new HashSet<SKUMASTER>();
        }
    
        public int ICDEPT_KEY { get; set; }
        public string ICDEPT_CODE { get; set; }
        public string ICDEPT_THAIDESC { get; set; }
        public string ICDEPT_ENGDESC { get; set; }
        public short ICDEPT_ACCESS { get; set; }
        public Nullable<int> ICDEPT_LEVEL { get; set; }
        public Nullable<int> ICDEPT_ABS_INDEX { get; set; }
        public Nullable<int> ICDEPT_PARENT { get; set; }
        public Nullable<int> ICDEPT_P_ABS_INDEX { get; set; }
        public Nullable<int> ICDEPT_FIRSTCHILD { get; set; }
        public decimal ICDEPT_UDF_1 { get; set; }
        public decimal ICDEPT_UDF_2 { get; set; }
        public decimal ICDEPT_UDF_3 { get; set; }
        public decimal ICDEPT_UDF_4 { get; set; }
        public decimal ICDEPT_UDF_5 { get; set; }
        public decimal ICDEPT_UDF_6 { get; set; }
        public string ICDEPT_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUMASTER> SKUMASTERs { get; set; }
    }
}
