//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCMLINE
    {
        public int INCMSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public int REFDOCSEQ { get; set; }
        public string DOCCODE { get; set; }
        public string REFDOC { get; set; }
        public decimal DOCDATE { get; set; }
        public decimal INCMDATE { get; set; }
        public string TRANSCODE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal INCMVALUES { get; set; }
        public int ACCMAPKEY { get; set; }
        public string ACCOUNTNO { get; set; }
        public string AUDITUSER { get; set; }
        public System.DateTime AUDITDATE { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
