//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVLINE
    {
        public int INVLINESEQ { get; set; }
        public bool ISDELETE { get; set; }
        public bool ISCANCEL { get; set; }
        public int SALETYPE { get; set; }
        public int SOLINESEQ { get; set; }
        public int SOSEQ { get; set; }
        public string SALEORDERNO { get; set; }
        public int INVSEQ { get; set; }
        public string INVOICENO { get; set; }
        public int SERVICECHARGEID { get; set; }
        public string JOBNO { get; set; }
        public string PO { get; set; }
        public int ITEMID { get; set; }
        public string PREFIX { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string UNIT { get; set; }
        public decimal SALEQTY { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal NETPRICE { get; set; }
        public decimal FINALPRICE { get; set; }
        public decimal VATRATE { get; set; }
        public decimal VATVALUE { get; set; }
        public decimal LINETOTAL { get; set; }
        public int MATID { get; set; }
        public decimal TOTALWEIGHT { get; set; }
        public string INVLINEREMARK { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
