//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public bool ISDELETE { get; set; }
        public bool ISCANCEL { get; set; }
        public decimal CANCELDATE { get; set; }
        public string CANCELBY { get; set; }
        public bool VATABLE { get; set; }
        public bool ISCHEQUE { get; set; }
        public int SALETYPE { get; set; }
        public string STATUS { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public string INVPREFIX { get; set; }
        public string REFCODE { get; set; }
        public string INVCOUNT { get; set; }
        public int INVOICEID { get; set; }
        public string INVOICENO { get; set; }
        public decimal INVDATE { get; set; }
        public string INVDESCRIPTION { get; set; }
        public Nullable<int> FISCYEAR { get; set; }
        public Nullable<int> FISCPERIOD { get; set; }
        public decimal INVVALUE { get; set; }
        public decimal INVDISCOUNT { get; set; }
        public decimal INVNETVALUE { get; set; }
        public decimal INVVATRATE { get; set; }
        public decimal INVVATVALUE { get; set; }
        public decimal WHTAXRATE { get; set; }
        public decimal INVWHTAX { get; set; }
        public decimal INVTOTALAMOUNT { get; set; }
        public string INVTOTALAMOUNTTEXT { get; set; }
        public decimal INVACTUALPAYMENT { get; set; }
        public string INVACTUALPAYMENTTEXT { get; set; }
        public string REMARK { get; set; }
        public string INVCANCELREASON { get; set; }
        public string PAYCODE { get; set; }
        public string CHEQUENO { get; set; }
        public decimal PAYDATE { get; set; }
        public string RECEIPTNO { get; set; }
        public decimal COLLECTDATE { get; set; }
        public Nullable<int> BANKID { get; set; }
        public string BANKCODE { get; set; }
        public int BILLID { get; set; }
        public string BILLNO { get; set; }
        public decimal BILLDATE { get; set; }
        public decimal DUEDATE { get; set; }
        public Nullable<int> OVERDUEDAYS { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
