//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMSPRICELIST
    {
        public int SPID { get; set; }
        public bool ISACTIVE { get; set; }
        public int EFFECTIVE { get; set; }
        public int EXPIRE { get; set; }
        public string ITEMID { get; set; }
        public string ITEMNAME { get; set; }
        public string FOR_MACHINE { get; set; }
        public string UNIT { get; set; }
        public decimal THB_UNITCOST { get; set; }
        public decimal THB_UNITPRICE { get; set; }
        public decimal SOURCE_FACTOR { get; set; }
        public decimal USD_UNITPRICE { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime LASTUPDATE { get; set; }
    }
}
