//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMCODE
    {
        public int ITEMCODEID { get; set; }
        public string ITEMCODE1 { get; set; }
        public string ITEMCODENAME_EN { get; set; }
        public string ITEMCODENAME_TH { get; set; }
    }
}
