//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBINFO
    {
        public int LINESEQ { get; set; }
        public bool ISDELETE { get; set; }
        public int FGLINESEQ { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public int JOBNO { get; set; }
        public string GROUPCODE { get; set; }
        public Nullable<int> MATERIALID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string ITEMPREFIX { get; set; }
        public string ITEMNO { get; set; }
        public decimal FINISHDATE { get; set; }
        public Nullable<int> FISCYEAR { get; set; }
        public Nullable<int> FISCPERIOD { get; set; }
        public Nullable<int> OPERATORID { get; set; }
        public string OPERATORNAME { get; set; }
        public decimal ACCEPTQTY { get; set; }
        public decimal REJECTQTY { get; set; }
        public decimal TOTALQTY { get; set; }
        public decimal TOTALWEIGHT { get; set; }
        public decimal AVGWEIGHT { get; set; }
        public decimal GOODSCORE { get; set; }
        public decimal BADSCORE { get; set; }
        public int ERRORID { get; set; }
        public string FLASK_TEMP { get; set; }
        public string CAST_TEMP { get; set; }
        public string RECORDEDBY { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    
        public virtual JOBORDER JOBORDER { get; set; }
    }
}
