//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15 {
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
	using static Shared.OMShareSysConfigEnums;

	public partial class LOGINEF : DbContext
	{
		public LOGINEF()
			: base("name=LOGINEF")
		{
		}
	
		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}
	
		public virtual DbSet<COMPANY_PROFILES> COMPANY_PROFILES { get; set; }
		public virtual DbSet<LOGIN> LOGINs { get; set; }
		public virtual DbSet<USERLOG> USERLOGs { get; set; }

	}
}
