//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenace1
    {
        public string s_order { get; set; }
        public string cus_na { get; set; }
        public string type { get; set; }
        public string s_no { get; set; }
        public string error { get; set; }
        public string detial { get; set; }
        public string month { get; set; }
        public Nullable<System.DateTime> year { get; set; }
        public string enginame { get; set; }
        public string nprice1 { get; set; }
        public string nprice2 { get; set; }
        public string nprice3 { get; set; }
        public string yprice1 { get; set; }
        public string ytal1 { get; set; }
        public string yprice2 { get; set; }
        public string ytal2 { get; set; }
        public string yprice3 { get; set; }
        public Nullable<byte> proviso { get; set; }
    }
}
