//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public int matseq { get; set; }
        public int matid { get; set; }
        public string matcategory { get; set; }
        public string thmatname { get; set; }
        public string enmatname { get; set; }
        public string usedtype { get; set; }
    }
}
