//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATOPENBALANCE
    {
        public int ID { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTNAME { get; set; }
        public string MATCAT { get; set; }
        public int OPENYEAR { get; set; }
        public decimal BALANCE1 { get; set; }
        public decimal BALANCE2 { get; set; }
        public decimal BALANCE3 { get; set; }
        public decimal BALANCE4 { get; set; }
        public decimal BALANCE5 { get; set; }
        public decimal BALANCE6 { get; set; }
        public decimal BALANCE7 { get; set; }
        public decimal BALANCE8 { get; set; }
        public decimal BALANCE9 { get; set; }
        public decimal BALANCE10 { get; set; }
        public decimal BALANCE11 { get; set; }
        public decimal BALANCE12 { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
    }
}
