//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRECEIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATRECEIVE()
        {
            this.CUSTMATRETURNs = new HashSet<CUSTMATRETURN>();
        }
    
        public int GRVSEQ { get; set; }
        public bool ISDELETE { get; set; }
        public bool ISCOMPLETE { get; set; }
        public bool ISFORSALE { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public int MATTYPE { get; set; }
        public int RECEIVEUNIT { get; set; }
        public int SOSEQ { get; set; }
        public string REFSONUMBER { get; set; }
        public string CUSTDOCNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string RECEIVERNAME { get; set; }
        public decimal RECEIVEDATE { get; set; }
        public decimal RECEIVEWEIGHT { get; set; }
        public decimal TOTALCLEARING { get; set; }
        public decimal BALANCEWEIGHT { get; set; }
        public string SENDERNAME { get; set; }
        public decimal SENDINGDATE { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTMATRETURN> CUSTMATRETURNs { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
