//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATSTOCK
    {
        public int SKLINE { get; set; }
        public bool ISDELETE { get; set; }
        public string CUSTCODE { get; set; }
        public int CUSTID { get; set; }
        public int REFORGISEQ { get; set; }
        public string REFDOC { get; set; }
        public decimal SKDATE { get; set; }
        public int ITEMSEQ { get; set; }
        public string APPTYPE { get; set; }
        public int SKTYPE { get; set; }
        public int MATTYPE { get; set; }
        public string MATUNIT { get; set; }
        public decimal MATWT { get; set; }
        public decimal CONVFACTOR { get; set; }
        public decimal CONVMATWT { get; set; }
        public string ACTIONBY { get; set; }
        public string REMARK { get; set; }
        public string WORKSTATION { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
