//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATSALE
    {
        public int MATID { get; set; }
        public string MATNAME { get; set; }
        public int COMPATMATID { get; set; }
        public decimal CONVERTFACTOR { get; set; }
    }
}
