//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCBOM
    {
        public int ID { get; set; }
        public bool ISACTIVE { get; set; }
        public string MODEL { get; set; }
        public int LEVEL { get; set; }
        public int POSITION { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string REF_NO { get; set; }
        public int REF_REV { get; set; }
        public string PARTNO { get; set; }
        public Nullable<int> PART_REV { get; set; }
        public string ITEMNAME { get; set; }
        public string DRAWINGNO { get; set; }
        public string CATEGORY { get; set; }
        public string UNIT { get; set; }
        public decimal UNITCOST { get; set; }
        public decimal Qty { get; set; }
        public string SIZE { get; set; }
        public string MATERIAL { get; set; }
        public string MAKER { get; set; }
        public string PROCESS { get; set; }
        public decimal PROCESS_COST { get; set; }
    }
}
