//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIX
    {
        public string productid { get; set; }
        public bool isdelete { get; set; }
        public bool isexpire { get; set; }
        public bool isnewproduct { get; set; }
        public bool istransfer { get; set; }
        public Nullable<System.DateTime> transferdate { get; set; }
        public int mix_id { get; set; }
        public string type { get; set; }
        public string s_no { get; set; }
        public string cus_na { get; set; }
        public int custid { get; set; }
        public string acccustcode { get; set; }
        public int qtysale { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public int yearsale { get; set; }
        public int monthsale { get; set; }
        public int warrantyterm { get; set; }
        public int monthfactor { get; set; }
        public Nullable<System.DateTime> exp { get; set; }
        public int yearexpire { get; set; }
        public int monthexpire { get; set; }
        public string remark { get; set; }
        public string audituser { get; set; }
        public Nullable<System.DateTime> auditdt { get; set; }
        public string modiuser { get; set; }
        public Nullable<System.DateTime> modidt { get; set; }
    }
}
