//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_SUM_AGING
    {
        public string Expr1 { get; set; }
        public Nullable<decimal> DUE { get; set; }
        public Nullable<decimal> OVER_1_30 { get; set; }
        public Nullable<decimal> OVER_31_60 { get; set; }
        public Nullable<decimal> OVER_61_90 { get; set; }
        public Nullable<decimal> OVER_91_120 { get; set; }
        public Nullable<decimal> OVER_121_150 { get; set; }
        public Nullable<decimal> OVER_151_180 { get; set; }
        public Nullable<decimal> OVER_180 { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
    }
}
