//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_BILLING
    {
        public string STATUS { get; set; }
        public bool ISCOMPLETE { get; set; }
        public int FISCYEAR { get; set; }
        public int FISCPERIOD { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTNAME { get; set; }
        public string SALE_TYPE { get; set; }
        public int BILLID { get; set; }
        public string BILLNO { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> COLLECT_DATE { get; set; }
        public decimal TOTALVALUE { get; set; }
        public decimal DISCOUNT { get; set; }
        public decimal NETVALUE { get; set; }
        public decimal VATFACTOR { get; set; }
        public decimal TOTALVAT { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public string TOTALTEXT { get; set; }
        public string INVOICENO { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public Nullable<int> INV_YEAR { get; set; }
        public Nullable<int> INV_PERIOD { get; set; }
        public decimal TOTALPAYVALUE { get; set; }
        public decimal TOTALWHTAX { get; set; }
    }
}
