//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_SALES
    {
        public string SALECAT { get; set; }
        public int FISCYEAR { get; set; }
        public int FISCPERIOD { get; set; }
        public string CUSTNAME { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public string CATEGORY { get; set; }
        public string MATERIAL { get; set; }
        public decimal DELIVERWEIGHT { get; set; }
    }
}
