//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_GRV_INFO
    {
        public int GRVSEQ { get; set; }
        public Nullable<int> GRV_YEAR { get; set; }
        public Nullable<int> GRV_MONTH { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CATEGORY { get; set; }
        public int MATTYPE { get; set; }
        public string ENKEYNAME { get; set; }
        public decimal RECEIVEWEIGHT { get; set; }
        public decimal TOTALCLEARING { get; set; }
        public decimal BALANCEWEIGHT { get; set; }
    }
}
