//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_ITEMPRICE
    {
        public int PRICESEQ { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTNAME { get; set; }
        public string PREFIX { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public int PRODUCTSTYLE { get; set; }
        public string STYLE { get; set; }
        public int MATERIAL { get; set; }
        public string MAT { get; set; }
        public string UNITCOUNT { get; set; }
        public decimal CASTINGPRICE { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal SCOREPRICE { get; set; }
        public decimal WAXWEIGHT { get; set; }
        public decimal UNITWEIGHT { get; set; }
        public string CAST_TEMP { get; set; }
        public string FLASK_TEMP { get; set; }
        public string IMAGE_LOCATION { get; set; }
    }
}
