//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CASTING_AGING
    {
        public string CUSTNAME { get; set; }
        public decimal ON_DUE { get; set; }
        public decimal OVER_1_30 { get; set; }
        public decimal OVER_31_60 { get; set; }
        public decimal OVER_61_90 { get; set; }
        public decimal OVER_91_120 { get; set; }
        public decimal OVER_121_150 { get; set; }
        public decimal OVER_151_180 { get; set; }
        public decimal OVER_181 { get; set; }
        public decimal TOTAL { get; set; }
    }
}
