//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_DELIVERY_CASTING_ITEM_R
    {
        public int JOBNO { get; set; }
        public decimal DELIVEREDQTY { get; set; }
        public decimal NETTUNITVALUE { get; set; }
        public Nullable<decimal> TOTAL_VALUES { get; set; }
        public Nullable<int> Y { get; set; }
    }
}
