//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_SKU_BALANCE
    {
        public int SKB_DI { get; set; }
        public int SKU_KEY { get; set; }
        public int SKU_ICCAT { get; set; }
        public string ICCAT_NAME { get; set; }
        public string SKU_CODE { get; set; }
        public string SKU_NAME { get; set; }
        public int SKB_WL { get; set; }
        public string WL_CODE { get; set; }
        public string WL_NAME { get; set; }
        public decimal SKB_QTY { get; set; }
        public decimal SKB_UTQQTY { get; set; }
        public decimal SKB_U_PRC { get; set; }
        public decimal SKB_COST { get; set; }
        public System.DateTime SKB_DATE { get; set; }
        public Nullable<int> SKB_YEAR { get; set; }
        public Nullable<int> SKB_MONTH { get; set; }
    }
}
