//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_PRODUCTION_DOCYEAR
    {
        public string DOC_REF { get; set; }
        public Nullable<int> DOC_YEAR { get; set; }
        public int DI_DT { get; set; }
    }
}
