//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_DOCINFO
    {
        public int DI_KEY { get; set; }
        public int DI_DT { get; set; }
        public int DT_KEY { get; set; }
        public string DT_DOCCODE { get; set; }
        public string DT_PREFIX { get; set; }
        public Nullable<int> DT_PROPERTIES { get; set; }
        public string DT_THAIDESC { get; set; }
        public string DT_ENGDESC { get; set; }
        public string DI_REF { get; set; }
        public System.DateTime DI_DATE { get; set; }
        public Nullable<int> DI_YEAR { get; set; }
        public Nullable<int> DI_MONTH { get; set; }
        public decimal DI_1ST_AMOUNT { get; set; }
        public decimal DI_AMOUNT { get; set; }
        public string DI_REMARK { get; set; }
    }
}
