//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_WH_ISSUE_ITEMS
    {
        public int ISSUELINEID { get; set; }
        public string ORDERNUMBER { get; set; }
        public int PROJECTNO { get; set; }
        public int DOCUMENTKEY { get; set; }
        public string DOCUMENTNO { get; set; }
        public System.DateTime DOCUMENTDATE { get; set; }
        public int ICKEY { get; set; }
        public string ICCODE { get; set; }
        public string ICNAME { get; set; }
        public int DEPARTMENTID { get; set; }
        public string DEPARTMENTCODE { get; set; }
        public string SHIPITEMNO { get; set; }
        public string SHIPITEMNAME { get; set; }
        public string SHIPUNIT { get; set; }
        public decimal SHIPQTY { get; set; }
        public decimal SHIPUNITPRICE { get; set; }
        public decimal SHIPTOTALVALUE { get; set; }
        public decimal SHIPTOTALVAT { get; set; }
        public decimal SHIPGRANDTOTAL { get; set; }
    }
}
