//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_TRH_TRD
    {
        public int TRH_KEY { get; set; }
        public int TRH_DI { get; set; }
        public Nullable<System.DateTime> TRH_CANCEL_DATE { get; set; }
        public int TRH_DEPT { get; set; }
        public decimal TRH_N_QTY { get; set; }
        public string TRH_REMARK { get; set; }
        public Nullable<int> TRH_SHIP_ADDB { get; set; }
        public System.DateTime TRH_SHIP_DATE { get; set; }
        public Nullable<int> TRH_SHIP_YEAR { get; set; }
        public Nullable<int> TRH_SHIP_MONTH { get; set; }
        public int TRD_KEY { get; set; }
        public int TRD_TRH { get; set; }
        public int TRD_SKU { get; set; }
        public int TRD_GOODS { get; set; }
        public decimal TRD_QTY { get; set; }
        public decimal TRD_Q_FREE { get; set; }
        public decimal TRD_U_PRC { get; set; }
        public decimal TRD_UTQQTY { get; set; }
        public string TRD_UTQNAME { get; set; }
        public string TRD_SH_CODE { get; set; }
        public string TRD_SH_NAME { get; set; }
        public decimal TRD_SH_QTY { get; set; }
        public decimal TRD_SH_UPRC { get; set; }
        public decimal TRD_SH_GSELL { get; set; }
        public decimal TRD_SH_GVAT { get; set; }
        public decimal TRD_SH_GAMT { get; set; }
        public string TRD_SH_REMARK { get; set; }
        public Nullable<int> TRD_REFER_DI { get; set; }
        public string TRD_REFER_REF { get; set; }
        public Nullable<System.DateTime> TRD_REFER_DATE { get; set; }
    }
}
