//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_CUSTOMER
    {
        public int ERPCUSTOMERID { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string PROVINCE { get; set; }
        public string POSTAL { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEB { get; set; }
        public string BRANCH { get; set; }
        public string TAXID { get; set; }
        public string CATEGORYNAME { get; set; }
        public int CATEGORYKEY { get; set; }
        public int CUSTOMERCATEGORYKEY { get; set; }
    }
}
