//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_PRODUCTION_PROJECT
    {
        public int PRJ_KEY { get; set; }
        public string STATUS { get; set; }
        public string PRJ_CODE { get; set; }
        public string PRJ_NAME { get; set; }
        public Nullable<System.DateTime> PRJ_FM_DATE { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string PRJ_REMARK { get; set; }
    }
}
