//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_STOCK_MOVE
    {
        public int DI_KEY { get; set; }
        public string DI_REF { get; set; }
        public System.DateTime DI_DATE { get; set; }
        public Nullable<int> DI_YEAR { get; set; }
        public Nullable<int> DI_MONTH { get; set; }
        public string SKU_CODE { get; set; }
        public string SKU_NAME { get; set; }
        public decimal SKM_QTY { get; set; }
        public decimal SKM_COST { get; set; }
        public decimal SKM_VAT { get; set; }
        public decimal DI_AMOUNT { get; set; }
        public decimal SKM_SELL { get; set; }
        public string DI_REMARK { get; set; }
    }
}
