//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_PRODUCTION_TRANSFER_REQUEST
    {
        public int DI_KEY { get; set; }
        public string STATUS { get; set; }
        public string CODE { get; set; }
        public string DI_REF { get; set; }
        public Nullable<System.DateTime> REQ_DATE { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UNIT { get; set; }
        public string REMARK { get; set; }
    }
}
