//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_WH_ITEM_CLASS
    {
        public int ICCAT_KEY { get; set; }
        public string ICCAT_CODE { get; set; }
        public string CAT_NAME { get; set; }
        public string ITEM_CLASS { get; set; }
        public int SKB_WL { get; set; }
        public string WL_CODE { get; set; }
        public int ID { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string UNIT { get; set; }
        public decimal STD_COST { get; set; }
        public decimal ON_HAND { get; set; }
        public decimal SKB_COST { get; set; }
        public decimal SKU_MIN_QTY { get; set; }
        public decimal SKU_MAX_ORDER { get; set; }
    }
}
