//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ERP_WH_STOCK_ITEM_INFO
    {
        public int CAT_KEY { get; set; }
        public string CAT_CODE { get; set; }
        public int SKB_WL { get; set; }
        public string WL_CODE { get; set; }
        public string CATEGORY { get; set; }
        public int ID { get; set; }
        public string CLASS { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string UNIT { get; set; }
        public decimal UNIT_COST { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal ON_HAND { get; set; }
        public decimal MIN_QTY { get; set; }
        public decimal MIN_ORDER { get; set; }
        public decimal MAX_QTY { get; set; }
        public decimal MAX_ORDER { get; set; }
    }
}
