//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_FS_VALIDTIME_RECORDS
    {
        public int USERID { get; set; }
        public string Badgenumber { get; set; }
        public string Name { get; set; }
        public string EMPCODE { get; set; }
        public string fname { get; set; }
        public Nullable<System.DateTime> DateOnly { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> D { get; set; }
        public Nullable<int> I { get; set; }
        public Nullable<int> O { get; set; }
        public Nullable<int> Avail_Hour { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
    }
}
