//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_JOB_ITEM_R
    {
        public Nullable<int> FISCYEAR { get; set; }
        public int JOBNO { get; set; }
        public string GROUPCODE { get; set; }
        public string OPERATORNAME { get; set; }
        public Nullable<decimal> QTY { get; set; }
    }
}
