//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_PRODUCTION_MISS_REPORT
    {
        public string WORKERNAME { get; set; }
        public Nullable<System.DateTime> LASTWORKDATE { get; set; }
        public System.DateTime TODAY { get; set; }
        public Nullable<int> DAYOFMISSREPORT { get; set; }
    }
}
