//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_PRODUCTION_WORKINGTIMES
    {
        public int RecordId { get; set; }
        public string ProductionJob { get; set; }
        public string WorkDate { get; set; }
        public string WorkerId { get; set; }
        public string WorkerName { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string DrawingNo { get; set; }
        public int ProcessId { get; set; }
        public string ProcessName { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<System.DateTime> OTFrom { get; set; }
        public Nullable<System.DateTime> OTEnd { get; set; }
        public decimal TotalTime { get; set; }
        public decimal GoodQty { get; set; }
        public decimal BadQty { get; set; }
        public decimal TotalQty { get; set; }
        public decimal InProcessQty { get; set; }
    }
}
