//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_SALE_MC_RECORD
    {
        public bool isnewproduct { get; set; }
        public bool istransfer { get; set; }
        public string acccustcode { get; set; }
        public string cus_na { get; set; }
        public string type { get; set; }
        public string s_no { get; set; }
        public int yearsale { get; set; }
        public int monthsale { get; set; }
        public Nullable<int> Q { get; set; }
    }
}
