//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_SUM_DEL_CASTING_R
    {
        public Nullable<int> Y { get; set; }
        public int JOBNO { get; set; }
        public decimal NETTUNITVALUE { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
