//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_SRV_MACHINE_SERVICE
    {
        public int fiscyear { get; set; }
        public string orderCode { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> JAN { get; set; }
        public Nullable<int> FEB { get; set; }
        public Nullable<int> MAR { get; set; }
        public Nullable<int> APR { get; set; }
        public Nullable<int> MAY { get; set; }
        public Nullable<int> JUN { get; set; }
        public Nullable<int> JUL { get; set; }
        public Nullable<int> AUG { get; set; }
        public Nullable<int> SEP { get; set; }
        public Nullable<int> OCT { get; set; }
        public Nullable<int> NOV { get; set; }
        public Nullable<int> DEC { get; set; }
        public Nullable<int> TOTAL { get; set; }
    }
}
