//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_VALID_TIME_RECORDS
    {
        public int IndRegID { get; set; }
        public string fname { get; set; }
        public string DateOnlyRecord { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> M { get; set; }
        public Nullable<int> D { get; set; }
        public Nullable<int> I { get; set; }
        public Nullable<int> O { get; set; }
        public Nullable<int> Avail_Hour { get; set; }
    }
}
