//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERSPAREPART
    {
        public int spLine { get; set; }
        public string issueno { get; set; }
        public System.DateTime dateneed { get; set; }
        public int orderid { get; set; }
        public string ordercode { get; set; }
        public string s_order { get; set; }
        public bool indatabase { get; set; }
        public string itemno { get; set; }
        public string itemname { get; set; }
        public string uom { get; set; }
        public decimal qtyneed { get; set; }
        public decimal ucost { get; set; }
        public decimal uprice { get; set; }
        public decimal discount { get; set; }
        public decimal netuprice { get; set; }
        public decimal totalprice { get; set; }
        public string itemremark { get; set; }
        public bool isdelete { get; set; }
        public string audituser { get; set; }
        public Nullable<System.DateTime> auditdt { get; set; }
        public string modiuser { get; set; }
        public Nullable<System.DateTime> modidt { get; set; }
    
        public virtual ORDERMAINTENANCE ORDERMAINTENANCE { get; set; }
    }
}
