//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDITEMPROCESS
    {
        public int ID { get; set; }
        public int REF_STDITEM { get; set; }
        public string REF_STDITEMNO { get; set; }
        public int STEP { get; set; }
        public int REF_PROCESS { get; set; }
        public string MATID { get; set; }
        public string MATNAME { get; set; }
        public decimal WORKMINT { get; set; }
        public decimal STD_HR { get; set; }
        public decimal HOUR_FACTOR { get; set; }
        public decimal STEP_COST { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
