//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_ITEMS
    {
        public int PI_ITEM { get; set; }
        public int REF_INDEX { get; set; }
        public int PI_ID { get; set; }
        public string PI_ITEMNO { get; set; }
        public string PI_ITEMNAME { get; set; }
        public decimal PI_ITEM_QTY { get; set; }
        public string PI_ITEM_UNIT { get; set; }
        public decimal PI_ITEM_PRICE { get; set; }
        public decimal PI_ITEM_AMOUNT { get; set; }
        public string PI_ITEM_REMARK { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
    }
}
