//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_INVOICE
    {
        public int PIID { get; set; }
        public int PI_YEAR { get; set; }
        public int PI_COUNT { get; set; }
        public string PINO { get; set; }
        public System.DateTime PI_DATE { get; set; }
        public int PI_CUSTID { get; set; }
        public string PI_CUSTCODE { get; set; }
        public string PI_CUSTNAME { get; set; }
        public string PI_ADDRESS { get; set; }
        public string PI_COUNTRY { get; set; }
        public string PI_BANKINFO { get; set; }
        public string PI_CURRENCY { get; set; }
        public string PI_DELIVERY_TIME { get; set; }
        public string PI_DELIVERY_TERM { get; set; }
        public string PI_PAYMENT_TERM { get; set; }
        public decimal PI_LINE_TOTAL { get; set; }
        public decimal PI_PACKING { get; set; }
        public decimal PI_DELIVERY { get; set; }
        public decimal PI_TOTAL_VALUES { get; set; }
        public string CREATEUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime LASTUPDATE { get; set; }
    }
}
