//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMMC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMMC()
        {
            this.PMSCHEDULEs = new HashSet<PMSCHEDULE>();
        }
    
        public int PM_MC { get; set; }
        public string CONTRACT_KEY { get; set; }
        public string PM_MC_MODEL { get; set; }
        public string PM_MC_SN { get; set; }
        public int PM_TYPE_KEY { get; set; }
        public int PM_MAX { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    
        public virtual PMCONTRACT PMCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMSCHEDULE> PMSCHEDULEs { get; set; }
    }
}
