//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSCHEDULE
    {
        public bool isdelete { get; set; }
        public bool iscomplete { get; set; }
        public int sch_id { get; set; }
        public int MC_Key { get; set; }
        public int PM_series { get; set; }
        public Nullable<System.DateTime> PMDate { get; set; }
        public Nullable<System.DateTime> ActualPMDate { get; set; }
        public string PMJobNo { get; set; }
        public string AUDITUSER { get; set; }
        public Nullable<System.DateTime> LASTMODIFY { get; set; }
    
        public virtual PMMC PMMC { get; set; }
    }
}
