//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDPROCESS
    {
        public int PRDPROCESSID { get; set; }
        public string PROCESSNAME { get; set; }
        public string MACHINE { get; set; }
        public decimal STDHOUR { get; set; }
        public decimal SCORE { get; set; }
    }
}
