//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICELIST
    {
        public int prseq { get; set; }
        public bool isdelete { get; set; }
        public bool isexpire { get; set; }
        public int materialid { get; set; }
        public int pricegroup { get; set; }
        public string custcod { get; set; }
        public string itemno { get; set; }
        public string itemname { get; set; }
        public int style { get; set; }
        public string unitcount { get; set; }
        public decimal stdunitprice { get; set; }
        public decimal waxcastingprice { get; set; }
        public decimal masterwaxprice { get; set; }
        public decimal cutsizeprice { get; set; }
        public int itemscore { get; set; }
        public Nullable<decimal> itemwaxweight { get; set; }
        public Nullable<decimal> itemweight { get; set; }
        public decimal priceeffectdate { get; set; }
        public decimal priceexpiredate { get; set; }
        public byte[] itemimg { get; set; }
    }
}
