//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRINTLOG
    {
        public int LOGID { get; set; }
        public string DOCID { get; set; }
        public string DOCNAME { get; set; }
        public System.DateTime PRINT_DT { get; set; }
        public string PRINT_BY { get; set; }
    }
}
