//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJTAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRJTAB()
        {
            this.TRANSTKHs = new HashSet<TRANSTKH>();
        }
    
        public int PRJ_KEY { get; set; }
        public string PRJ_CODE { get; set; }
        public string PRJ_NAME { get; set; }
        public string PRJ_ENABLE { get; set; }
        public Nullable<System.DateTime> PRJ_FM_DATE { get; set; }
        public Nullable<System.DateTime> PRJ_TO_DATE { get; set; }
        public string PRJ_REMARK { get; set; }
        public decimal PRJ_UDF_1 { get; set; }
        public decimal PRJ_UDF_2 { get; set; }
        public decimal PRJ_UDF_3 { get; set; }
        public decimal PRJ_UDF_4 { get; set; }
        public decimal PRJ_UDF_5 { get; set; }
        public decimal PRJ_UDF_6 { get; set; }
        public string PRJ_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSTKH> TRANSTKHs { get; set; }
    }
}
