//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTIONJOBINFO
    {
        public int PRDINFOID { get; set; }
        public int WORKCAT { get; set; }
        public string ERP_ORDER { get; set; }
        public int PROCESSID { get; set; }
        public int STEP { get; set; }
        public string PROCESSNAME { get; set; }
        public string PROCESSDETAIL { get; set; }
        public Nullable<int> MACHINEID { get; set; }
        public Nullable<int> MACHINEGROUP { get; set; }
        public string MACHINENAME { get; set; }
        public string COSTCENTER { get; set; }
        public string WORKERID { get; set; }
        public string WORKERNAME { get; set; }
        public string ITEMNO { get; set; }
        public string DRAWINGNO { get; set; }
        public string TIME_CAT { get; set; }
        public Nullable<System.DateTime> DATETIME_START { get; set; }
        public Nullable<System.DateTime> DATETIME_END { get; set; }
        public decimal TOTAL_NORMAL_HR { get; set; }
        public decimal BREAK_HRS { get; set; }
        public Nullable<System.DateTime> OT_START { get; set; }
        public Nullable<System.DateTime> OT_END { get; set; }
        public decimal OT_BREAK { get; set; }
        public decimal TOTAL_OT_HR { get; set; }
        public Nullable<int> WORKYEAR { get; set; }
        public Nullable<int> WORKPERIOD { get; set; }
        public Nullable<int> WORKDAY { get; set; }
        public decimal INPROCESS_QTY { get; set; }
        public decimal GOOD_QTY { get; set; }
        public decimal BAD_QTY { get; set; }
        public decimal TOTALQTY { get; set; }
        public decimal TOTAL_HRS { get; set; }
        public decimal REGULAR_HR_RATE { get; set; }
        public decimal NET85_HR_RATE { get; set; }
        public decimal NET75_HR_RATE { get; set; }
        public decimal AVG85_HR_RATE { get; set; }
        public decimal AVG75_HR_RATE { get; set; }
        public decimal TOTAL_COST { get; set; }
        public decimal TOTAL_COST85 { get; set; }
        public decimal TOTAL_COST75 { get; set; }
        public decimal TOTAL_AVG_COST85 { get; set; }
        public decimal TOTAL_AVG_COST75 { get; set; }
        public string REMARK { get; set; }
        public string CREATEUSER { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string MODIUSER { get; set; }
        public System.DateTime MODIDATE { get; set; }
    }
}
