//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_OUTSOURCE
    {
        public int Id { get; set; }
        public string ERP_ORDER { get; set; }
        public string AP_CODE { get; set; }
        public string AP_NAME { get; set; }
        public System.DateTime DATESTART { get; set; }
        public Nullable<System.DateTime> DATEFINISH { get; set; }
        public string BUILD_DETAIL { get; set; }
        public int STEP { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string DRAWINGNO { get; set; }
        public string DRAWING_REV { get; set; }
        public decimal BUILD_QTY { get; set; }
        public string UNIT { get; set; }
        public decimal MATERIAL_COST { get; set; }
        public decimal LABOR_COST { get; set; }
        public decimal OTHER_COST { get; set; }
        public decimal TOTAL_COST { get; set; }
    }
}
