//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_MC_MEMBER
    {
        public int ID { get; set; }
        public int MC_GROUP { get; set; }
        public string MC_NAME { get; set; }
        public string MC_NUMBER { get; set; }
    }
}
