//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTIONSTDITEM
    {
        public int ItemId { get; set; }
        public bool islock { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public string DrawingNo { get; set; }
        public int DrawingRev { get; set; }
        public System.DateTime DrawingDate { get; set; }
        public string SheetNo { get; set; }
        public string MatNo { get; set; }
        public string Material { get; set; }
        public decimal UnitWeight { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal WorktimeMint { get; set; }
        public decimal STDProductHours { get; set; }
        public decimal ProducionHourCost { get; set; }
        public decimal ProductionCost { get; set; }
        public decimal ItemCost { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModiUser { get; set; }
        public System.DateTime ModiDate { get; set; }
    }
}
