//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_WH_RECEIVE
    {
        public int RECEIVEID { get; set; }
        public string REF_TRANSFER_DOC { get; set; }
        public int REF_ISSUE_ID { get; set; }
        public string RECEIVE_NO { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public string RECEIVE_UNIT { get; set; }
        public decimal RECEIVE_QTY { get; set; }
        public decimal RECEIVE_COST { get; set; }
        public decimal RECEIVE_AVG_UCOST { get; set; }
        public string RECEIVE_BY { get; set; }
    }
}
