//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATIONLL
    {
        public int QL_ID { get; set; }
        public int QL_REFID { get; set; }
        public int QL_QT { get; set; }
        public string QL_ITEMNO { get; set; }
        public string QL_ITEMNAME { get; set; }
        public string QL_ITEMINFO { get; set; }
        public string QL_UNIT { get; set; }
        public string QL_CURRENCY { get; set; }
        public decimal QL_UNITPRICE { get; set; }
        public decimal QL_QTY { get; set; }
        public decimal QL_TOTAL { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
