//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTATIONHH
    {
        public int QT_ID { get; set; }
        public int QT_REF_KEY { get; set; }
        public bool QT_MASTER { get; set; }
        public bool QT_INBOUND { get; set; }
        public int QT_STATUS { get; set; }
        public string QT_PREFIX { get; set; }
        public string QT_NUMBER { get; set; }
        public int QT_REVISION { get; set; }
        public int QT_COUNT { get; set; }
        public Nullable<int> QT_YEAR { get; set; }
        public System.DateTime QT_DATE { get; set; }
        public System.DateTime QT_VALIDATIONDATE { get; set; }
        public string QT_CUSTOMER { get; set; }
        public int QT_CUSTID { get; set; }
        public string QT_CUSTCODE { get; set; }
        public string QT_ADDRESS { get; set; }
        public string QT_COUNTRY { get; set; }
        public string QT_CONTACT_PERSON { get; set; }
        public string QT_CONTACTNO { get; set; }
        public string QT_CUST_EMAIL { get; set; }
        public string QT_SALE_PERSON { get; set; }
        public string QT_SALE_CONTACTNO { get; set; }
        public string QT_SALE_EMAIL { get; set; }
        public string QT_CURRENCY { get; set; }
        public decimal QT_TOTALVALUEITEMS { get; set; }
        public decimal QT_PERCENTDISCOUNT { get; set; }
        public decimal QT_TOTALDISCOUNT { get; set; }
        public decimal QT_EXTRADISCOUNT { get; set; }
        public decimal QT_TOTALNETTVALUES { get; set; }
        public decimal QT_VATRATE { get; set; }
        public decimal QT_VATVALUES { get; set; }
        public Nullable<decimal> QT_TOTALGOODSAMT { get; set; }
        public decimal QT_PACKINGVALUE { get; set; }
        public decimal QT_SHIPPINGVALUE { get; set; }
        public decimal QT_TOTALAMOUNT { get; set; }
        public string QT_DELIVERY_TERM { get; set; }
        public string QT_PAYMENT_TERM { get; set; }
        public string QT_BANKINFO { get; set; }
        public string QT_WARRANTY { get; set; }
        public string QT_DELIVERY_TIME { get; set; }
        public string QT_TRAINING { get; set; }
        public string QT_REMARK { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
