//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBBERBASE
    {
        public int BASEID { get; set; }
        public bool INACTIVE { get; set; }
        public string BASENO { get; set; }
        public string BASESIZE { get; set; }
        public decimal WEIGHTGRAM { get; set; }
        public string REMARK { get; set; }
    }
}
