//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_CONTACTS
    {
        public int CONTACT_ID { get; set; }
        public string CONTACT_NAME { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public string COMPANY { get; set; }
        public string ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public string POSTAL { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
    }
}
