//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMAN
    {
        public int SLMN_KEY { get; set; }
        public string SLMN_CODE { get; set; }
        public string SLMN_NAME { get; set; }
        public string SLMN_REMARK { get; set; }
        public int SLMN_SLCAT { get; set; }
        public int SLMN_CMRH { get; set; }
        public int SLMN_AC { get; set; }
        public int SLMN_SLL { get; set; }
        public int SLMN_SLU { get; set; }
        public int SLMN_SLT { get; set; }
        public int SLMN_SLR { get; set; }
        public string SLMN_ENABLE { get; set; }
        public decimal SLMN_UDF_1 { get; set; }
        public decimal SLMN_UDF_2 { get; set; }
        public decimal SLMN_UDF_3 { get; set; }
        public decimal SLMN_UDF_4 { get; set; }
        public decimal SLMN_UDF_5 { get; set; }
        public decimal SLMN_UDF_6 { get; set; }
        public string SLMN_LASTUPD { get; set; }
    }
}
