//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_PERSON_PROFILE
    {
        public int SALEID { get; set; }
        public bool ISACTIVE { get; set; }
        public string SALE_PERSON { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
    }
}
