//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKUMOVE
    {
        public int SKM_KEY { get; set; }
        public int SKM_SKU { get; set; }
        public int SKM_DI { get; set; }
        public int SKM_WL { get; set; }
        public Nullable<int> SKM_REFER_DI { get; set; }
        public string SKM_LOT_NO { get; set; }
        public string SKM_SERIAL { get; set; }
        public decimal SKM_QTY { get; set; }
        public decimal SKM_COST { get; set; }
        public decimal SKM_SELL { get; set; }
        public decimal SKM_VAT { get; set; }
        public decimal SKM_B4_DISC { get; set; }
        public decimal SKM_AF_GP { get; set; }
        public decimal SKM_Q_FREE { get; set; }
        public Nullable<System.DateTime> SKM_EXP_D { get; set; }
        public Nullable<System.DateTime> SKM_MAN_D { get; set; }
        public Nullable<int> SKM_SHOW_ORDER { get; set; }
        public int SKM_AC { get; set; }
        public string SKM_LASTUPD { get; set; }
    
        public virtual DOCINFO DOCINFO { get; set; }
        public virtual SKUMASTER SKUMASTER { get; set; }
    }
}
