//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLINE
    {
        public int SOLINESEQ { get; set; }
        public bool ISCOMPLETE { get; set; }
        public bool ISDELETE { get; set; }
        public Nullable<System.Guid> SO_GUID { get; set; }
        public int REFSOKEY { get; set; }
        public int FGLINESEQ { get; set; }
        public int SALETYPE { get; set; }
        public int CUSTID { get; set; }
        public string CUSTCODE { get; set; }
        public int SOSEQ { get; set; }
        public string SONO { get; set; }
        public decimal DELIVERDATE { get; set; }
        public int JOBNO { get; set; }
        public string PO { get; set; }
        public int ITEMID { get; set; }
        public string PREFIX { get; set; }
        public string ITEMNO { get; set; }
        public string ITEMNAME { get; set; }
        public string UNIT { get; set; }
        public decimal DELIVEREDQTY { get; set; }
        public bool ISMATINCLUDE { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal UNITDISCOUNT { get; set; }
        public decimal NETTUNITVALUE { get; set; }
        public decimal TOTALVALUE { get; set; }
        public decimal VATFACTOR { get; set; }
        public decimal VATVALUE { get; set; }
        public decimal LINEAMOUNT { get; set; }
        public int MATTYPE { get; set; }
        public decimal TOTALWEIGHT { get; set; }
        public decimal AVGUNITWEIGHT { get; set; }
        public decimal AVGPRICEUNITWEIGHT { get; set; }
        public string SOLINEREMARK { get; set; }
        public string AUDITUSER { get; set; }
        public System.DateTime AUDITDATE { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
