//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPCOST
    {
        public int id { get; set; }
        public string s_order { get; set; }
        public string yprice2 { get; set; }
        public string dtool { get; set; }
        public string ytal2 { get; set; }
        public decimal sparepartcost { get; set; }
        public bool isdelete { get; set; }
    }
}
