//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSDATA
    {
        public int LINESEQ { get; set; }
        public string CATEGORY { get; set; }
        public string GROUPTITLE { get; set; }
        public string ENKEYNAME { get; set; }
        public string KEYVALUE { get; set; }
        public string THKEYNAME { get; set; }
        public string GROUPTITLEHEADER { get; set; }
        public decimal CONVERTFACTOR { get; set; }
        public decimal MATFACTOR { get; set; }
        public decimal SI { get; set; }
        public decimal FURNACETEMP { get; set; }
        public decimal CASTINGTEMP { get; set; }
    }
}
