//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSTKH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSTKH()
        {
            this.TRANSTKDs = new HashSet<TRANSTKD>();
        }
    
        public int TRH_KEY { get; set; }
        public int TRH_DI { get; set; }
        public Nullable<int> TRH_PSTATUS { get; set; }
        public Nullable<int> TRH_LSTATUS { get; set; }
        public Nullable<int> TRH_FLAG { get; set; }
        public int TRH_DEPT { get; set; }
        public int TRH_BR { get; set; }
        public int TRH_MKTP { get; set; }
        public int TRH_PRMT { get; set; }
        public string TRH_ARPRB { get; set; }
        public decimal TRH_N_QTY { get; set; }
        public Nullable<int> TRH_N_ITEMS { get; set; }
        public string TRH_REMARK { get; set; }
        public int TRH_SB { get; set; }
        public string TRH_SHIP_REMARK { get; set; }
        public System.DateTime TRH_SHIP_DATE { get; set; }
        public Nullable<int> TRH_SHIP_ADDB { get; set; }
        public short TRH_VAT_TY { get; set; }
        public decimal TRH_VAT { get; set; }
        public decimal TRH_VAT_R { get; set; }
        public Nullable<int> TRH_VATIO { get; set; }
        public int TRH_PRJ { get; set; }
        public Nullable<System.DateTime> TRH_CANCEL_DATE { get; set; }
        public Nullable<System.DateTime> TRH_LAST_DATE { get; set; }
        public Nullable<int> TRH_OPTION { get; set; }
        public string TRH_REFER_XREF { get; set; }
        public string TRH_REFER_IREF { get; set; }
        public string TRH_REFER_PERSON { get; set; }
        public string TRH_REFER_XTRA1 { get; set; }
        public string TRH_REFER_XTRA2 { get; set; }
        public Nullable<int> TRH_TAP { get; set; }
        public string TRH_LASTUPD { get; set; }
    
        public virtual DEPTTAB DEPTTAB { get; set; }
        public virtual DOCINFO DOCINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSTKD> TRANSTKDs { get; set; }
        public virtual PRJTAB PRJTAB { get; set; }
    }
}
