//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSTKD
    {
        public int TRD_KEY { get; set; }
        public int TRD_TRH { get; set; }
        public Nullable<int> TRD_SEQ { get; set; }
        public int TRD_GOODS { get; set; }
        public string TRD_KEYIN { get; set; }
        public short TRD_VAT_TY { get; set; }
        public decimal TRD_VAT { get; set; }
        public decimal TRD_VAT_R { get; set; }
        public decimal TRD_NM_PRC { get; set; }
        public Nullable<int> TRD_NM_VATIO { get; set; }
        public string TRD_NM_U_DSC { get; set; }
        public decimal TRD_QTY { get; set; }
        public decimal TRD_Q_FREE { get; set; }
        public decimal TRD_K_U_PRC { get; set; }
        public decimal TRD_U_PRC { get; set; }
        public Nullable<int> TRD_U_VATIO { get; set; }
        public string TRD_DSC_KEYIN { get; set; }
        public decimal TRD_DSC_KEYINV { get; set; }
        public decimal TRD_G_KEYIN { get; set; }
        public decimal TRD_G_SELL { get; set; }
        public decimal TRD_G_VAT { get; set; }
        public decimal TRD_G_AMT { get; set; }
        public decimal TRD_TDSC_KEYINV { get; set; }
        public decimal TRD_N_SELL { get; set; }
        public decimal TRD_N_VAT { get; set; }
        public decimal TRD_N_AMT { get; set; }
        public decimal TRD_B_SELL { get; set; }
        public decimal TRD_B_VAT { get; set; }
        public decimal TRD_B_AMT { get; set; }
        public Nullable<int> TRD_B_GROUP { get; set; }
        public decimal TRD_B_RELOCATE { get; set; }
        public decimal TRD_B_UPRC { get; set; }
        public int TRD_SKU { get; set; }
        public decimal TRD_UTQQTY { get; set; }
        public string TRD_UTQNAME { get; set; }
        public decimal TRD_WEIGHT { get; set; }
        public short TRD_COST_TY { get; set; }
        public short TRD_WH_TY { get; set; }
        public decimal TRD_WH_RATE { get; set; }
        public decimal TRD_WH_TAX { get; set; }
        public string TRD_LOT_NO { get; set; }
        public string TRD_SERIAL { get; set; }
        public Nullable<System.DateTime> TRD_EXP_D { get; set; }
        public Nullable<System.DateTime> TRD_MAN_D { get; set; }
        public Nullable<int> TRD_WL { get; set; }
        public Nullable<int> TRD_TO_WL { get; set; }
        public string TRD_SH_AUTO { get; set; }
        public string TRD_SH_CODE { get; set; }
        public string TRD_SH_NAME { get; set; }
        public decimal TRD_SH_QTY { get; set; }
        public decimal TRD_SH_UPRC { get; set; }
        public decimal TRD_SH_GSELL { get; set; }
        public decimal TRD_SH_GVAT { get; set; }
        public decimal TRD_SH_GAMT { get; set; }
        public string TRD_SH_REMARK { get; set; }
        public decimal TRD_RTN_UPRC { get; set; }
        public decimal TRD_RTN_AMT { get; set; }
        public decimal TRD_COMM_RATE { get; set; }
        public decimal TRD_COMM_AMT { get; set; }
        public int TRD_AC { get; set; }
        public decimal TRD_UQTY { get; set; }
        public decimal TRD_UQ_FREE { get; set; }
        public Nullable<int> TRD_OPTION { get; set; }
        public string TRD_REFER_REF { get; set; }
        public Nullable<System.DateTime> TRD_REFER_DATE { get; set; }
        public Nullable<int> TRD_REFER_DI { get; set; }
        public Nullable<int> TRD_REFER_TRH { get; set; }
        public Nullable<int> TRD_REFER_TRD { get; set; }
        public decimal TRD_OR_QTY { get; set; }
        public decimal TRD_OR_U_PRC { get; set; }
        public decimal TRD_OR_DSC_KEYINV { get; set; }
        public decimal TRD_OR_G_KEYIN { get; set; }
        public decimal TRD_OR_Q_FREE { get; set; }
        public decimal TRD_AC_QTY { get; set; }
        public decimal TRD_AC_G_KEYIN { get; set; }
        public decimal TRD_AC_Q_FREE { get; set; }
        public decimal TRD_NX_QTY { get; set; }
        public string TRD_NX_DSC_KEYIN { get; set; }
        public decimal TRD_NX_DSC_KEYINV { get; set; }
        public decimal TRD_NX_G_KEYIN { get; set; }
        public decimal TRD_NX_Q_FREE { get; set; }
        public decimal TRD_ADJ_PAMT { get; set; }
        public decimal TRD_ADJ_MAMT { get; set; }
        public decimal TRD_B_PCNT { get; set; }
        public Nullable<int> TRD_PRICE { get; set; }
        public string TRD_EQ_FACTOR { get; set; }
        public decimal TRD_EQ_V { get; set; }
        public Nullable<int> TRD_CAMPAIGN { get; set; }
        public Nullable<int> TRD_ARCPGN { get; set; }
        public string TRD_ARCPGN_C { get; set; }
        public decimal TRD_C_U_PRC { get; set; }
        public string TRD_C_DSC { get; set; }
        public decimal TRD_C_DSCV { get; set; }
        public string TRD_CONSIGN { get; set; }
        public string TRD_CNSN_B4 { get; set; }
        public Nullable<int> TRD_CREATOR { get; set; }
        public Nullable<int> TRD_SKUALT { get; set; }
        public Nullable<int> TRD_ASRTH { get; set; }
        public Nullable<int> TRD_ICCOLOR { get; set; }
        public decimal TRD_ASRT_QTY { get; set; }
        public decimal TRD_ASRT_FREE { get; set; }
        public decimal TRD_ASRT_U_PRC { get; set; }
        public string TRD_ASRT_U_DSC { get; set; }
        public string TRD_LASTUPD { get; set; }
    
        public virtual TRANSTKH TRANSTKH { get; set; }
    }
}
