//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOFQTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UOFQTY()
        {
            this.SKUBALANCEs = new HashSet<SKUBALANCE>();
            this.SKUMASTERs = new HashSet<SKUMASTER>();
            this.SKUMASTERs1 = new HashSet<SKUMASTER>();
            this.SKUMASTERs2 = new HashSet<SKUMASTER>();
            this.GOODSMASTERs = new HashSet<GOODSMASTER>();
        }
    
        public int UTQ_KEY { get; set; }
        public string UTQ_NAME { get; set; }
        public decimal UTQ_QTY { get; set; }
        public string UTQ_LASTUPD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUBALANCE> SKUBALANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUMASTER> SKUMASTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUMASTER> SKUMASTERs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKUMASTER> SKUMASTERs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODSMASTER> GOODSMASTERs { get; set; }
    }
}
