//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPERMISSION
    {
        public int USERSEQ { get; set; }
        public string USERNAME { get; set; }
        public string USERPWD { get; set; }
        public int PERMISSIONID { get; set; }
        public string PERMISSIONCLASS { get; set; }
        public bool ISACTIVE { get; set; }
    }
}
