//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMW15
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAXTREE
    {
        public int WAXTREEID { get; set; }
        public decimal BUILDDATE { get; set; }
        public Nullable<int> FISCYEAR { get; set; }
        public string CUSTCODE { get; set; }
        public int CUSTID { get; set; }
        public string RUBBERBASENO { get; set; }
        public decimal BASEWEIGHT { get; set; }
        public decimal BASENWAXWG { get; set; }
        public decimal ACTUALWAX { get; set; }
        public int MATCASTING { get; set; }
        public decimal MATFACTOR { get; set; }
        public decimal MATADDWEIGHT { get; set; }
        public decimal MATWEIGHTBF { get; set; }
        public decimal ACTUALMATWEIGHT { get; set; }
        public decimal MATWEIGHTAF { get; set; }
        public decimal SLAG { get; set; }
        public decimal MATWEIGHTLOSS { get; set; }
        public string ALLOYTYPE { get; set; }
        public decimal ALLOYWEIGHT { get; set; }
        public decimal SILVER100 { get; set; }
        public decimal SILVER95 { get; set; }
        public decimal SILVER94 { get; set; }
        public Nullable<decimal> GOLD100 { get; set; }
        public string OTHERMAT { get; set; }
        public decimal OTHERMATWEIGHT { get; set; }
        public decimal WEIGHTWITHCONTAINER { get; set; }
        public int TOTALCOUNTWAX { get; set; }
        public decimal FURNACETEMP { get; set; }
        public decimal CASTINGTEMP { get; set; }
        public decimal ACTUALTEMP { get; set; }
        public string REMARK { get; set; }
        public string CASTINGBY { get; set; }
        public bool ISDELETE { get; set; }
        public string AUDITUSER { get; set; }
        public string MODIUSER { get; set; }
        public Nullable<System.DateTime> MODIDATE { get; set; }
    }
}
