CREATE VIEW OM_ACTUAL_PRODUCTION_HOUR_BY_WORKER
AS
SELECT 
pj.WORKYEAR,
pj.WORKERID,
pj.WORKERNAME,
'jan'= SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'feb'= SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'mar'= SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'apr'= SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'may'= SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'jun'= SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'jul'= SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'aug'= SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'sep'= SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'oct'= SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'nov'= SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'dec'= SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_NORMAL_HR ELSE 0 END),
'TotalNT'= SUM(pj.TOTAL_NORMAL_HR)
FROM PRODUCTIONJOBINFO pj
INNER JOIN (
SELECT DISTINCT 
u.SSN,
'dd' = CAST(chk.CHECKTIME AS date)
FROM Fingerscan.dbo.CHECKINOUT chk 
LEFT JOIN FingerScan.dbo.USERINFO u ON chk.USERID = u.USERID
) a
ON pj.WORKERID = a.SSN 
AND CAST(pj.DATETIME_START AS date) = a.dd
GROUP BY pj.WORKYEAR,pj.WORKERID,pj.WORKERNAME
