CREATE VIEW OM_CASTING_AVG_PRICE_GRAM AS
SELECT
a.Y,
a.MAT,
'jan' = AVG(a.jan),
'feb' = AVG(a.feb),
'mar' = AVG(a.mar),
'apr' = AVG(a.apr),
'may' = AVG(a.may),
'jun' = AVG(a.jun),
'jul' = AVG(a.jul),
'aug' = AVG(a.aug),
'sep' = AVG(a.sep),
'oct' = AVG(a.oct),
'nov' = AVG(a.nov),
'dec' = AVG(a.dec),
'avg' = AVG(a.avg)
FROM (
SELECT 
'Y' =SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),1,4),
'MAT' = (SELECT da.CATEGORY FROM SYSDATA da WHERE da.GROUPTITLE='MATERIAL' AND CAST(da.KEYVALUE AS INT) = sl.MATTYPE),
'jan' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 1 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'feb' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 2 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'mar' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 3 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'apr' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 4 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'may' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 5 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'jun' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 6 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'jul' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 7 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'aug' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 8 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'sep' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 9 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'oct' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 10 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'nov' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 11 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'dec' = AVG(CASE WHEN CAST(SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),5,2) AS INT) = 12 THEN sl.AVGPRICEUNITWEIGHT ELSE 0 END),
'AVG' = AVG(sl.AVGPRICEUNITWEIGHT)
FROM SOLINES sl
WHERE sl.PREFIX = 'R'
--AND SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),1,4) = '2020'
GROUP BY sl.MATTYPE,SUBSTRING(CAST(sl.DELIVERDATE AS VARCHAR(8)),1,4))  a
GROUP BY a.Y,a.MAT
