ALTER VIEW OM_PRODUCTION_COST_HOURS
AS
SELECT
pi.ERP_ORDER,
pi.WORKERID,
pi.WORKERNAME,
pi.ITEMNO,
pi.PROCESSNAME,
pi.PROCESSDETAIL,
pi.TOTAL_NORMAL_HR,
pi.TOTAL_OT_HR,
pi.TOTALQTY,
pi.GOOD_QTY,
pi.BAD_QTY,
pi.WORKYEAR,
pi.WORKPERIOD,
'HOUR_COST' = ISNULL(eh.AVGHOURCOST,0),
'ACTUAL_HR_COST' = ISNULL(eh.ACTUALAVGHOURCOST,0),
ep.PRD_AVGHOURCOST,
ep.PRD_ACTUALAVGHOURCOST

FROM PRODUCTIONJOBINFO pi
LEFT JOIN EMPSAL es ON pi.WORKERID = es.EMPCODE AND es.YEARSAL = pi.WORKYEAR
LEFT JOIN (
SELECT
es.EMPCODE,
es.YEARSAL,
es.AVGHOURCOST,
es.ACTUALAVGHOURCOST
FROM EMPSAL es 
) eh ON pi.WORKERID = eh.EMPCODE AND pi.WORKYEAR = eh.YEARSAL
LEFT JOIN (
SELECT
es.YEARSAL,
'PRD_AVGHOURCOST'=AVG(es.AVGHOURCOST),
'PRD_ACTUALAVGHOURCOST' = AVG(es.ACTUALAVGHOURCOST)
FROM EMPSAL es 
WHERE es.WORKGROUP = 'PRODUCTION'
GROUP BY es.YEARSAL ) ep ON pi.WORKYEAR = ep.YEARSAL