-- SELECT
-- a.WORKYEAR
-- , a.WORKERNAME
-- , [jan-NT] = SUM(CASE WHEN a.WORKPERIOD = 1 THEN a.[jan-NT] ELSE 0 END)
-- , [feb-NT] = SUM(CASE WHEN a.WORKPERIOD = 2 THEN a.[feb-NT] ELSE 0 END)
-- , [mar-NT] = SUM(CASE WHEN a.WORKPERIOD = 3 THEN a.[mar-NT] ELSE 0 END)
-- , [apr-NT] = SUM(CASE WHEN a.WORKPERIOD = 4 THEN a.[apr-NT] ELSE 0 END)
-- , [may-NT] = SUM(CASE WHEN a.WORKPERIOD = 5 THEN a.[may-NT] ELSE 0 END)
-- , [jun-NT] = SUM(CASE WHEN a.WORKPERIOD = 6 THEN a.[jun-NT] ELSE 0 END)
-- , [jul-NT] = SUM(CASE WHEN a.WORKPERIOD = 7 THEN a.[jul-NT] ELSE 0 END)
-- , [aug-NT] = SUM(CASE WHEN a.WORKPERIOD = 8 THEN a.[aug-NT] ELSE 0 END)
-- , [sep-NT] = SUM(CASE WHEN a.WORKPERIOD = 9 THEN a.[sep-NT] ELSE 0 END)
-- , [oct-NT] = SUM(CASE WHEN a.WORKPERIOD = 10 THEN a.[oct-NT] ELSE 0 END)
-- , [nov-NT] = SUM(CASE WHEN a.WORKPERIOD = 11 THEN a.[nov-NT] ELSE 0 END)
-- , [dec-NT] = SUM(CASE WHEN a.WORKPERIOD = 12 THEN a.[dec-NT] ELSE 0 END)
-- , [Total-NT] = SUM(a.[Total-NT])
-- FROM (select 
--pj.WORKYEAR
--,pj.WORKPERIOD
--,pj.WORKERNAME
--,'jan-NT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jan-OT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jan-TT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_HRS ELSE 0 END)
--,'feb-NT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'feb-OT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'feb-TT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_HRS ELSE 0 END)
--,'mar-NT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'mar-OT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'mar-TT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_HRS ELSE 0 END)
--,'apr-NT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'apr-OT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'apr-TT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_HRS ELSE 0 END)
--,'may-NT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'may-OT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'may-TT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_HRS ELSE 0 END)
--,'jun-NT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jun-OT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jun-TT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_HRS ELSE 0 END)
--,'jul-NT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jul-OT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jul-TT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_HRS ELSE 0 END)
--,'aug-NT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'aug-OT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'aug-TT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_HRS ELSE 0 END)
--,'sep-NT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'sep-OT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'sep-TT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_HRS ELSE 0 END)
--,'oct-NT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'oct-OT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'oct-TT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_HRS ELSE 0 END)
--,'nov-NT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'nov-OT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'nov-TT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_HRS ELSE 0 END)
--,'dec-NT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'dec-OT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'dec-TT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_HRS ELSE 0 END)
--,'Total-NT' = SUM(pj.TOTAL_NORMAL_HR)
--,'Total-OT' = SUM(pj.TOTAL_OT_HR)
--,'Total-TT' = SUM(pj.TOTAL_HRS)
--from PRODUCTIONJOBINFO pj
--where ERP_ORDER = 'BU50P-60+FEED-18'
--GROUP BY pj.WORKYEAR,pj.WORKERNAME,pj.WORKPERIOD ) a
--GROUP BY a.WORKYEAR,a.WORKERNAME


-- SELECT
-- a.WORKYEAR
-- , a.WORKERNAME
-- , [jan-OT] = SUM(CASE WHEN a.WORKPERIOD = 1 THEN a.[jan-OT] ELSE 0 END)
-- , [feb-OT] = SUM(CASE WHEN a.WORKPERIOD = 2 THEN a.[feb-OT] ELSE 0 END)
-- , [mar-OT] = SUM(CASE WHEN a.WORKPERIOD = 3 THEN a.[mar-OT] ELSE 0 END)
-- , [apr-OT] = SUM(CASE WHEN a.WORKPERIOD = 4 THEN a.[apr-OT] ELSE 0 END)
-- , [may-OT] = SUM(CASE WHEN a.WORKPERIOD = 5 THEN a.[may-OT] ELSE 0 END)
-- , [jun-OT] = SUM(CASE WHEN a.WORKPERIOD = 6 THEN a.[jun-OT] ELSE 0 END)
-- , [jul-OT] = SUM(CASE WHEN a.WORKPERIOD = 7 THEN a.[jul-OT] ELSE 0 END)
-- , [aug-OT] = SUM(CASE WHEN a.WORKPERIOD = 8 THEN a.[aug-OT] ELSE 0 END)
-- , [sep-OT] = SUM(CASE WHEN a.WORKPERIOD = 9 THEN a.[sep-OT] ELSE 0 END)
-- , [oct-OT] = SUM(CASE WHEN a.WORKPERIOD = 10 THEN a.[oct-OT] ELSE 0 END)
-- , [nov-OT] = SUM(CASE WHEN a.WORKPERIOD = 11 THEN a.[nov-OT] ELSE 0 END)
-- , [dec-OT] = SUM(CASE WHEN a.WORKPERIOD = 12 THEN a.[dec-OT] ELSE 0 END)
-- , [Total-OT] = SUM(a.[Total-OT])
-- FROM (select 
--pj.WORKYEAR
--,pj.WORKPERIOD
--,pj.WORKERNAME
--,'jan-NT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jan-OT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jan-TT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_HRS ELSE 0 END)
--,'feb-NT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'feb-OT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'feb-TT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_HRS ELSE 0 END)
--,'mar-NT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'mar-OT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'mar-TT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_HRS ELSE 0 END)
--,'apr-NT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'apr-OT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'apr-TT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_HRS ELSE 0 END)
--,'may-NT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'may-OT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'may-TT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_HRS ELSE 0 END)
--,'jun-NT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jun-OT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jun-TT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_HRS ELSE 0 END)
--,'jul-NT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'jul-OT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'jul-TT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_HRS ELSE 0 END)
--,'aug-NT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'aug-OT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'aug-TT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_HRS ELSE 0 END)
--,'sep-NT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'sep-OT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'sep-TT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_HRS ELSE 0 END)
--,'oct-NT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'oct-OT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'oct-TT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_HRS ELSE 0 END)
--,'nov-NT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'nov-OT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'nov-TT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_HRS ELSE 0 END)
--,'dec-NT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
--,'dec-OT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_OT_HR ELSE 0 END)
--,'dec-TT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_HRS ELSE 0 END)
--,'Total-NT' = SUM(pj.TOTAL_NORMAL_HR)
--,'Total-OT' = SUM(pj.TOTAL_OT_HR)
--,'Total-TT' = SUM(pj.TOTAL_HRS)
--from PRODUCTIONJOBINFO pj
--where ERP_ORDER = 'BU50P-60+FEED-18'
--GROUP BY pj.WORKYEAR,pj.WORKERNAME,pj.WORKPERIOD ) a
--GROUP BY a.WORKYEAR,a.WORKERNAME


 SELECT
 a.WORKYEAR
 , a.WORKERNAME
 , [jan-TT] = SUM(CASE WHEN a.WORKPERIOD = 1 THEN a.[jan-TT] ELSE 0 END)
 , [feb-TT] = SUM(CASE WHEN a.WORKPERIOD = 2 THEN a.[feb-TT] ELSE 0 END)
 , [mar-TT] = SUM(CASE WHEN a.WORKPERIOD = 3 THEN a.[mar-TT] ELSE 0 END)
 , [apr-TT] = SUM(CASE WHEN a.WORKPERIOD = 4 THEN a.[apr-TT] ELSE 0 END)
 , [may-TT] = SUM(CASE WHEN a.WORKPERIOD = 5 THEN a.[may-TT] ELSE 0 END)
 , [jun-TT] = SUM(CASE WHEN a.WORKPERIOD = 6 THEN a.[jun-TT] ELSE 0 END)
 , [jul-TT] = SUM(CASE WHEN a.WORKPERIOD = 7 THEN a.[jul-TT] ELSE 0 END)
 , [aug-TT] = SUM(CASE WHEN a.WORKPERIOD = 8 THEN a.[aug-TT] ELSE 0 END)
 , [sep-TT] = SUM(CASE WHEN a.WORKPERIOD = 9 THEN a.[sep-TT] ELSE 0 END)
 , [oct-TT] = SUM(CASE WHEN a.WORKPERIOD = 10 THEN a.[oct-TT] ELSE 0 END)
 , [nov-TT] = SUM(CASE WHEN a.WORKPERIOD = 11 THEN a.[nov-TT] ELSE 0 END)
 , [dec-TT] = SUM(CASE WHEN a.WORKPERIOD = 12 THEN a.[dec-TT] ELSE 0 END)
 , [Total-TT] = SUM(a.[Total-TT])
 FROM (select 
pj.WORKYEAR
,pj.WORKPERIOD
,pj.WORKERNAME
,'jan-NT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'jan-OT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'jan-TT' = SUM(CASE WHEN pj.WORKPERIOD = 1 THEN pj.TOTAL_HRS ELSE 0 END)
,'feb-NT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'feb-OT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'feb-TT' = SUM(CASE WHEN pj.WORKPERIOD = 2 THEN pj.TOTAL_HRS ELSE 0 END)
,'mar-NT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'mar-OT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'mar-TT' = SUM(CASE WHEN pj.WORKPERIOD = 3 THEN pj.TOTAL_HRS ELSE 0 END)
,'apr-NT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'apr-OT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'apr-TT' = SUM(CASE WHEN pj.WORKPERIOD = 4 THEN pj.TOTAL_HRS ELSE 0 END)
,'may-NT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'may-OT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'may-TT' = SUM(CASE WHEN pj.WORKPERIOD = 5 THEN pj.TOTAL_HRS ELSE 0 END)
,'jun-NT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'jun-OT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'jun-TT' = SUM(CASE WHEN pj.WORKPERIOD = 6 THEN pj.TOTAL_HRS ELSE 0 END)
,'jul-NT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'jul-OT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'jul-TT' = SUM(CASE WHEN pj.WORKPERIOD = 7 THEN pj.TOTAL_HRS ELSE 0 END)
,'aug-NT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'aug-OT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'aug-TT' = SUM(CASE WHEN pj.WORKPERIOD = 8 THEN pj.TOTAL_HRS ELSE 0 END)
,'sep-NT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'sep-OT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'sep-TT' = SUM(CASE WHEN pj.WORKPERIOD = 9 THEN pj.TOTAL_HRS ELSE 0 END)
,'oct-NT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'oct-OT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'oct-TT' = SUM(CASE WHEN pj.WORKPERIOD = 10 THEN pj.TOTAL_HRS ELSE 0 END)
,'nov-NT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'nov-OT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'nov-TT' = SUM(CASE WHEN pj.WORKPERIOD = 11 THEN pj.TOTAL_HRS ELSE 0 END)
,'dec-NT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_NORMAL_HR ELSE 0 END)
,'dec-OT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_OT_HR ELSE 0 END)
,'dec-TT' = SUM(CASE WHEN pj.WORKPERIOD = 12 THEN pj.TOTAL_HRS ELSE 0 END)
,'Total-NT' = SUM(pj.TOTAL_NORMAL_HR)
,'Total-OT' = SUM(pj.TOTAL_OT_HR)
,'Total-TT' = SUM(pj.TOTAL_HRS)
from PRODUCTIONJOBINFO pj
where ERP_ORDER = 'BU50P-60+FEED-18'
GROUP BY pj.WORKYEAR,pj.WORKERNAME,pj.WORKPERIOD
WITH ROLLUP
) a
GROUP BY a.WORKYEAR,a.WORKERNAME
WITH ROLLUP


