select 
sku.SKU_CODE,
sku.SKU_NAME,
utq.UTQ_NAME,
iccat.ICCAT_CODE,
trd.TRD_TO_WL,
trd.TRD_QTY,
trd.TRD_U_PRC,
trd.TRD_G_KEYIN
from TRANSTKD trd 
INNER JOIN TRANSTKH trh ON trd.TRD_TRH = trh.TRH_KEY
INNER JOIN SKUMASTER sku ON trd.TRD_SKU = sku.SKU_KEY
INNER JOIN ICCAT iccat ON sku.SKU_ICCAT = iccat.ICCAT_KEY
INNER JOIN UOFQTY utq ON sku.SKU_S_UTQ = utq.UTQ_KEY
INNER JOIN DOCINFO di ON trh.TRH_DI =di.DI_KEY 
INNER JOIN DOCTYPE dt ON di.DI_DT = dt.DT_KEY
where di.DI_REF LIKE 'FTM-PO10BU50P_V2%'
order by iccat.ICCAT_CODE desc
