
CREATE PROC dbo.usp_CastingAveragePriceByYear
@Year int = 0
AS

Declare @CurrentYear int = Year(getdate())

IF @Year > 0
	SET @CurrentYear = @Year

SELECT
a.CATEGORY,
a.FISCYEAR,
'jan'=MAX(CASE WHEN a.FISCPERIOD = 1 THEN a.[Month-Avg] ELSE 0 END),
'feb'=MAX(CASE WHEN a.FISCPERIOD = 2 THEN a.[Month-Avg] ELSE 0 END),
'mar'=MAX(CASE WHEN a.FISCPERIOD = 3 THEN a.[Month-Avg] ELSE 0 END),
'apr'=MAX(CASE WHEN a.FISCPERIOD = 4 THEN a.[Month-Avg] ELSE 0 END),
'may'=MAX(CASE WHEN a.FISCPERIOD = 5 THEN a.[Month-Avg] ELSE 0 END),
'jun'=MAX(CASE WHEN a.FISCPERIOD = 6 THEN a.[Month-Avg] ELSE 0 END),
'jul'=MAX(CASE WHEN a.FISCPERIOD = 7 THEN a.[Month-Avg] ELSE 0 END),
'aug'=MAX(CASE WHEN a.FISCPERIOD = 8 THEN a.[Month-Avg] ELSE 0 END),
'sep'=MAX(CASE WHEN a.FISCPERIOD = 9 THEN a.[Month-Avg] ELSE 0 END),
'oct'=MAX(CASE WHEN a.FISCPERIOD = 10 THEN a.[Month-Avg] ELSE 0 END),
'nov'=MAX(CASE WHEN a.FISCPERIOD = 11 THEN a.[Month-Avg] ELSE 0 END),
'dec'=MAX(CASE WHEN a.FISCPERIOD = 12 THEN a.[Month-Avg] ELSE 0 END),
'Avg' =AVG(a.[Month-Avg])
FROM (
SELECT
sd.CATEGORY,
so.FISCYEAR,
so.FISCPERIOD,
'Month-Avg' = AVG(sl.AVGPRICEUNITWEIGHT)
FROM SOLINES sl
INNER JOIN SALEORDERS so ON sl.SONO = so.SONO
INNER JOIN SYSDATA sd ON sl.MATTYPE = sd.KEYVALUE AND sd.GROUPTITLE = 'MATERIAL'
WHERE sl.PREFIX = 'R'
AND sl.SALETYPE <> 2
AND sl.ISDELETE = 0
AND sl.UNIT NOT IN ('ต้น')
AND sl.AVGUNITWEIGHT > 0
AND so.FISCYEAR = @CurrentYear
GROUP BY so.FISCYEAR,so.FISCPERIOD,sd.CATEGORY ) a
GROUP BY a.CATEGORY,a.FISCYEAR
ORDER BY a.FISCYEAR,a.CATEGORY